// createSlice is a utility from Redux Toolkit
// It helps us create reducer + action creators in one place
const { createSlice } = require("@reduxjs/toolkit");

// Create a slice for cart-related state
const cartSlice = createSlice({

  // Name of this slice (used internally by Redux)
  name: "cart",

  // Initial state of this slice in the Redux store
  initialState: {
    cartList: [], // Stores all products added to cart
    total: 0      // Stores total price of cart items
  },

  // Reducers define HOW the state should change
  reducers: {

    // Reducer to add a product to the cart
    add(state, action) {

      // action.payload contains the product being added

      // Create a new cart list by adding the product
      const updatedCartList = state.cartList.concat(action.payload);

      // Update total price by adding product price
      const total = state.total + action.payload.price;

      // Return updated state
      return {
        ...state,
        total: total,
        cartList: updatedCartList
      };
    },

    // Reducer to remove a product from the cart
    remove(state, action) {

      // action.payload contains the product to remove

      // Remove the product using its id
      const updatedCartList = state.cartList.filter(
        (cartItem) => cartItem.id !== action.payload.id
      );

      // Update total price by subtracting product price
      const total = state.total - action.payload.price;

      // Return updated state
      return {
        ...state,
        total: total,
        cartList: updatedCartList
      };
    }
  }
});

// Export action creators generated by createSlice
// These actions are dispatched from components
export const { add, remove } = cartSlice.actions;

// Export reducer to be used in Redux store
export const cartReducer = cartSlice.reducer;
